% 2014-12-04 18:05:15.593592749 +0100
%% human readable output of calibration properties
function backscatter_report(obj)
	fprintf(['Model : %d\n', ...
		 'Goodness of fit:\n', ...
                         '    rmse               = %f\n', ...
	         '    chi^2_red          = %f\n', ...
		 '    corr(M_ref, M_reg) = %f\n', ...
		 '    corr(err, depth)   = %f\n', ...
		 '    corr(err, time)    = %f\n', ...
		 '    err abnormality    = %d\n' ], ...
		 obj.model, obj.rmse, obj.chi2r, ...
		 obj.corrMM, obj.corred, obj.corret, ...
		 single(obj.abnormal));
%	fprintf(['Parameters and uncertainty with respect to 95%% confidence\n']);
%	fprintf(['    %d : %+5.3e +/- %5.3e\n'], ...
        %               [ (1:length(obj.param))' obj.param(:) obj.cparam(:,2)-obj.param(:)]');
	if (5 == obj.model)
		disp(sprintf('K : %e gamma : %e xi : %e \n', ...
                                      obj.param.mean(1), obj.param.mean(2), 5/log(10)*obj.param.mean(2)));
	end
	disp(sprintf('param mean: %g std %g\n',[obj.param.mean(:) obj.param.std(:)]'));
	disp(sprintf('corr: %f\n', obj.param.corr));
	btn = max(1,median(obj.btn)-1);
	disp(sprintf('std: %f bias %f\n', nanmean(mean(obj.M.std(1:btn,:),2)), ...
                                             nanmean(mean(obj.M.bias(1:btn,:),2)) ));
%	fprintf('Inhomogeneous parameters:');
%	fprintf( ' %d', obj.hparam);
%	fprintf('\n');
end % function report()

