% Mon 29 Jan 14:52:53 CET 2018
%% string of arguments, for file name generation
function str = optstr(opt)
	str = [ class(opt.velocity_profile) ...
		,'-',class(opt.sediment_concentration_profile) ...
		,'-smax-',num2str(opt.smax) ...
		, '-nl-', num2str(opt.vadcp.nlflag) ...
		, '-nbs-', num2str(opt.n_window.backscatter)];
end

